env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  quotes: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-restricted-syntax: 0
  no-unused-expressions: 0
